import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/globals.css';


export const metadata = {
  title: "Chat -APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}
